
# 填写爱发电的api
user: ''
token: ''

# 数据库信息 (推荐启用)
mysql-info:
  ip: '127.0.0.1'
  # 是否启用
  enable: false
  port: 3306
  param: 'useSSL=false&serverTimezone=Asia/Shanghai'
  user: 'root'
  password: '不告诉你'
  database: 'server01'
  validSql: 'show databases'

# 该选项控制多久开始查询一次订单
# 默认设置为 每两分钟 进行一次查询
# 你可以键入 0 */5 * * * * 进行五分钟一次查询
# 更灵活的时间可以参考 http://cron.ciding.cc/
query-cron: '0 0/2 * * * ?'

# 开启debug模式 (将在后台输出错误信息)
debug: false

# 网络请求超时时间 (秒)
timeout: 30